SUPABASE_URL = "https://zphrhtjooiggzieqcjji.supabase.co"
SUPABASE_SERVICE_ROLE = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwaHJodGpvb2lnZ3ppZXFjamppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5OTMxNjMsImV4cCI6MjA3NjU2OTE2M30.wxDp1cUhSGK9xFoTNZ2UdR0p6YoMpFU9e_VFSLypv34"   # Service Role Key
BUCKET_NAME = "kids-images"
APP_TZ = "Europe/Zurich"
